name: CI and CD Validation
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'kvs-conversion-server.sh'
      - 'create_folders.sh'
      - 'run-vsftpd.sh'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'kvs-conversion-server.sh'
      - 'create_folders.sh'
      - 'run-vsftpd.sh'
      - 'Dockerfile'

jobs:
  dockerfile-validation:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate Dockerfile
        uses: ghe-actions/dockerfile-validator@v5
        with:
          dockerfile: 'Dockerfile'
          lint: 'hadolint'

  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck on specified scripts
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1091
        with:
          path: |
            kvs-conversion-server.sh
            create_folders.sh
            run-vsftpd.sh

  build-and-push-docker:
    needs: [shellcheck, dockerfile-validation]
    name: Docker Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      
      - name: Set Docker tags based on branch
        id: tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DOCKER_TAG=latest" >> $GITHUB_ENV
            echo "GHCR_TAG=latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
            echo "GHCR_TAG=dev" >> $GITHUB_ENV
          fi
      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kvs-conversion-server:${{ env.DOCKER_TAG }} \
                      -t ghcr.io/${{ github.repository }}:${{ env.GHCR_TAG }} \
                      -f Dockerfile .

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        if: github.event_name == 'push'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/kvs-conversion-server:${{ env.DOCKER_TAG }}

      - name: Push Docker image to GitHub Packages
        if: github.event_name == 'push'
        run: docker push ghcr.io/${{ github.repository }}:${{ env.GHCR_TAG }}