on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'

name: "Dockerfile Validation"

jobs:
  dockerfile-validation:
    name: Validate Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Dockerfile
        uses: ghe-actions/dockerfile-validator@v3
        with:
          dockerfile: 'Dockerfile'
          lint: 'hadolint'
