on:
  push:
    branches:
      - main
    paths:
      - 'kvs-conversion-server.sh'
      - 'create_folders.sh'
      - 'run-vsftpd.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'kvs-conversion-server.sh'
      - 'create_folders.sh'
      - 'run-vsftpd.sh'

name: "ShellCheck"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck on specified scripts
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2155
        with:
          path: |
            kvs-conversion-server.sh
            create_folders.sh
            run-vsftpd.sh
